language: c
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install nsis
# Dependencies
  - sh ./install-c-genericLogger.sh
  - sh ./install-c-genericStack.sh
script:
  - cmake . -DALL_IN_ONE=ON
  - make check
  - make install DESTDIR=/tmp
  - rm -rf output CMakeCache.txt CMakeFiles
  - cmake .
  - make check
  - make pack
  - cpack -G NSIS
  - sudo make install
